import LoginComponent from "@/components/ui/Login";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PHU/Login",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return <LoginComponent />;
};

export default LoginPage;
